### ISSUE TITLE
Uploader issues in asp.net

### ISSUE THREAD

**Issue by amar4u** [brightcove-archive/ooyala_backlot-ingestion-library#7]
Presently I am using ooyala v1 up-loader  for uploading videos . I want to up grade my uploader to v2. 

I need some clarification : 

In v1 approach Browse button url   http://www.ooyala.com/partner/uploadButton?width=100&height=20&label=Browse

in case of v2 approach  what will be the url ? 

Please provide me c# or .net  example only.

**Comment by vidalon** [comment]
Please contact support@ooyala.com for these kind of questions, they might be able to answer faster than we can. If you want to know more about transitioning to our V2 API, you will find this useful: http://support.ooyala.com/developers/documentation/concepts/api_v1_v2_migration.html
